export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_STUDENTS_COMPLETION = 'FETCH_STUDENTS_COMPLETION';
export const SAVE_STUDENT = 'SAVE_STUDENT';
export const SAVE_STUDENT_ERROR = 'SAVE_STUDENT_ERROR';
export const DIALOG_TOGGLE = 'DIALOG_TOGGLE';
export const EDIT_STUDENT = 'EDIT_STUDENT';
